# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'project1' do

  # Pods for project1
  pod 'Firebase'
  pod 'FirebaseAuth', :modular_headers => true
  pod 'Firebase/Core', :modular_headers => true

  target 'project1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'project1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
