# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'project1' do
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  target 'project1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'project1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
